name: Elyzionite
url: http://elyzion.github.io
description: Random ramblings.

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
